// UniversalUIInspector.m — generic, read-only UIKit/runtime diagnostics.
// Public APIs only. No swizzling, patching, credential access, or target-specific classes.
#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>
#import <objc/runtime.h>
#import <mach-o/dyld.h>
#import <UniformTypeIdentifiers/UniformTypeIdentifiers.h>
#import <zlib.h>
#import <dlfcn.h>
#import <mach/mach.h>
#import <sys/stat.h>
#import <errno.h>

static NSString * const UIID = @"UniversalUIInspector";
static const NSUInteger kMaxStartupDepth = 8;
static const NSUInteger kMaxStartupNodes = 2000;

static NSString *ColorString(UIColor *c) {
    if (!c) return @"(nil)";
    CGFloat r=0,g=0,b=0,a=0;
    if ([c getRed:&r green:&g blue:&b alpha:&a]) return [NSString stringWithFormat:@"rgba(%.3f, %.3f, %.3f, %.3f)",r,g,b,a];
    CGFloat w=0;
    if ([c getWhite:&w alpha:&a]) return [NSString stringWithFormat:@"gray(%.3f, %.3f)",w,a];
    return c.description;
}
static NSString *LayerColorString(CGColorRef color) { return color ? ColorString([UIColor colorWithCGColor:color]) : @"(nil)"; }
static NSString *ViewLine(UIView *v) {
    return [NSString stringWithFormat:@"%@ %p frame=%@ bounds=%@ alpha=%.2f hidden=%@ bg=%@ layerBg=%@", NSStringFromClass(v.class),v,NSStringFromCGRect(v.frame),NSStringFromCGRect(v.bounds),v.alpha,v.hidden?@"YES":@"NO",ColorString(v.backgroundColor),LayerColorString(v.layer.backgroundColor)];
}

static NSURL *ReportsDirectory(void) {
    NSURL *documents = [[[NSFileManager defaultManager] URLsForDirectory:NSDocumentDirectory inDomains:NSUserDomainMask] firstObject];
    NSURL *dir = [documents URLByAppendingPathComponent:UIID isDirectory:YES];
    [[NSFileManager defaultManager] createDirectoryAtURL:dir withIntermediateDirectories:YES attributes:nil error:nil];
    return dir;
}
static void WriteReport(NSString *name, NSString *text) {
    NSURL *url = [ReportsDirectory() URLByAppendingPathComponent:name];
    [text writeToURL:url atomically:YES encoding:NSUTF8StringEncoding error:nil];
}
static NSString *ReportPath(NSString *name) { return [[ReportsDirectory() URLByAppendingPathComponent:name] path]; }

// Small uncompressed ZIP writer: creates a standards-compliant ZIP without third-party code.
static void ZipU16(NSMutableData *d, uint16_t v) { [d appendBytes:&v length:2]; }
static void ZipU32(NSMutableData *d, uint32_t v) { [d appendBytes:&v length:4]; }
static NSData *ZipData(NSDictionary<NSString *,NSData *> *files) {
    NSMutableData *zip=[NSMutableData data]; NSMutableArray<NSData *> *central=[NSMutableArray array];
    for (NSString *name in files) {
        NSData *data=files[name]; NSData *nameData=[name dataUsingEncoding:NSUTF8StringEncoding]; uint32_t crc=(uint32_t)crc32(0,(const Bytef *)data.bytes,(uInt)data.length); uint32_t size=(uint32_t)data.length; uint32_t offset=(uint32_t)zip.length;
        // Local file header: signature, version, UTF-8 flag, stored method, times, CRC, sizes, name and extra lengths.
        ZipU32(zip,0x04034b50); ZipU16(zip,20); ZipU16(zip,0x0800); ZipU16(zip,0); ZipU16(zip,0); ZipU16(zip,0); ZipU32(zip,crc); ZipU32(zip,size); ZipU32(zip,size); ZipU16(zip,(uint16_t)nameData.length); ZipU16(zip,0); [zip appendData:nameData]; [zip appendData:data];
        NSMutableData *c=[NSMutableData data];
        // Central directory header.
        ZipU32(c,0x02014b50); ZipU16(c,20); ZipU16(c,20); ZipU16(c,0x0800); ZipU16(c,0); ZipU16(c,0); ZipU16(c,0); ZipU32(c,crc); ZipU32(c,size); ZipU32(c,size); ZipU16(c,(uint16_t)nameData.length); ZipU16(c,0); ZipU16(c,0); ZipU16(c,0); ZipU16(c,0); ZipU32(c,0); ZipU32(c,offset); [c appendData:nameData]; [central addObject:c];
    }
    uint32_t centralOffset=(uint32_t)zip.length; for(NSData *c in central)[zip appendData:c]; uint32_t centralSize=(uint32_t)zip.length-centralOffset;
    ZipU32(zip,0x06054b50); ZipU16(zip,0); ZipU16(zip,0); ZipU16(zip,(uint16_t)central.count); ZipU16(zip,(uint16_t)central.count); ZipU32(zip,centralSize); ZipU32(zip,centralOffset); ZipU16(zip,0); return zip;
}


static BOOL ValidateZipArchive(NSData *data, NSUInteger *fileCount, NSString **reason) {
    const uint8_t *b=data.bytes; NSUInteger n=data.length; if(n<22){if(reason)*reason=@"archive shorter than EOCD";return NO;} NSInteger e=-1; for(NSInteger i=(NSInteger)n-22;i>=0 && i>(NSInteger)n-65558;i--){if(*(uint32_t *)(b+i)==0x06054b50){e=i;break;}} if(e<0){if(reason)*reason=@"end-of-central-directory signature not found";return NO;} uint16_t count=*(uint16_t *)(b+e+10); uint32_t size=*(uint32_t *)(b+e+12), off=*(uint32_t *)(b+e+16); if((NSUInteger)off+size>(NSUInteger)e){if(reason)*reason=@"central directory bounds invalid";return NO;} NSUInteger pos=off, seen=0; while(pos<(NSUInteger)off+size){if(pos+46>n || *(uint32_t *)(b+pos)!=0x02014b50){if(reason)*reason=@"central directory entry invalid";return NO;} uint16_t nl=*(uint16_t *)(b+pos+28), extra=*(uint16_t *)(b+pos+30), comment=*(uint16_t *)(b+pos+32); if(pos+46+nl+extra+comment>n){if(reason)*reason=@"central entry length invalid";return NO;} pos+=46+nl+extra+comment; seen++;} if(seen!=count){if(reason)*reason=[NSString stringWithFormat:@"entry count mismatch expected=%u seen=%lu",count,(unsigned long)seen];return NO;} if(fileCount)*fileCount=seen; return YES;
}


static uint64_t CurrentMemoryBytes(void) { mach_task_basic_info_data_t info; mach_msg_type_number_t count=MACH_TASK_BASIC_INFO_COUNT; kern_return_t kr=task_info(mach_task_self(),MACH_TASK_BASIC_INFO,(task_info_t)&info,&count); return kr==KERN_SUCCESS ? (uint64_t)info.resident_size : 0; }
static NSTimeInterval PhaseClock(void) { return CACurrentMediaTime(); }
static void AppendPhaseLog(NSString *phase, NSString *state, NSTimeInterval started, NSUInteger count, NSUInteger bytes, NSString *error) { NSString *line=[NSString stringWithFormat:@"%@ phase=%@ state=%@ elapsed_ms=%.1f count=%lu bytes=%lu memory_bytes=%llu error=%@\n",[NSDate date],phase,state,(PhaseClock()-started)*1000.0,(unsigned long)count,(unsigned long)bytes,(unsigned long long)CurrentMemoryBytes(),error ?: @"-"]; NSURL *u=[ReportsDirectory() URLByAppendingPathComponent:@"SESSION_PHASE_LOG.txt"]; NSFileHandle *h=[NSFileHandle fileHandleForWritingAtPath:u.path]; if(!h){[line writeToURL:u atomically:YES encoding:NSUTF8StringEncoding error:nil];return;} [h seekToEndOfFile]; [h writeData:[line dataUsingEncoding:NSUTF8StringEncoding]]; [h closeFile]; }
static NSData *BoundedFileData(NSURL *url, NSUInteger maxBytes, BOOL *truncated) { NSData *d=[NSData dataWithContentsOfURL:url]; if(d.length>maxBytes){if(truncated)*truncated=YES; return [d subdataWithRange:NSMakeRange(0,maxBytes)];} return d ?: [NSData data]; }
static NSUInteger WriteDetailedRuntimeReport(NSURL *url, NSUInteger maxClasses, NSUInteger maxMethods, NSUInteger maxBytes, BOOL *truncated, NSString **errorOut) {
    FILE *f=fopen(url.path.UTF8String,"wb"); if(!f){if(errorOut)*errorOut=[NSString stringWithFormat:@"open failed: %s",strerror(errno)];return 0;} NSUInteger classes=0,methods=0,bytes=0; int n=objc_getClassList(NULL,0); Class *cs=(Class *)malloc(sizeof(Class)*MAX(n,0)); n=objc_getClassList(cs,n); for(int i=0;i<n && classes<maxClasses && bytes<maxBytes;i++){Class c=cs[i]; const char *img=class_getImageName(c); if(img && (strstr(img,"/System/")||strstr(img,"/usr/lib/")||strstr(img,"/Developer/"))) continue; NSString *head=[NSString stringWithFormat:@"CLASS %@ : %@ image=%@\n",NSStringFromClass(c),NSStringFromClass(class_getSuperclass(c)),img ? [NSString stringWithUTF8String:img] : @"(nil)"]; NSData *hd=[head dataUsingEncoding:NSUTF8StringEncoding]; if(bytes+hd.length>maxBytes)break; fwrite(hd.bytes,1,hd.length,f);bytes+=hd.length;classes++; unsigned mc=0; Method *ms=class_copyMethodList(c,&mc); for(unsigned j=0;j<mc && methods<maxMethods && bytes<maxBytes;j++){Method m=ms[j]; NSString *line=[NSString stringWithFormat:@"  declared instance selector=%@ types=%s imp=%p\n",NSStringFromSelector(method_getName(m)),method_getTypeEncoding(m),method_getImplementation(m)]; NSData *ld=[line dataUsingEncoding:NSUTF8StringEncoding]; if(bytes+ld.length>maxBytes){if(truncated)*truncated=YES;break;} fwrite(ld.bytes,1,ld.length,f);bytes+=ld.length;methods++;} free(ms); if(bytes>=maxBytes){if(truncated)*truncated=YES;break;} mc=0; Method *cms=class_copyMethodList(object_getClass(c),&mc); for(unsigned j=0;j<mc && methods<maxMethods && bytes<maxBytes;j++){Method m=cms[j]; NSString *line=[NSString stringWithFormat:@"  declared class selector=%@ types=%s imp=%p\n",NSStringFromSelector(method_getName(m)),method_getTypeEncoding(m),method_getImplementation(m)]; NSData *ld=[line dataUsingEncoding:NSUTF8StringEncoding]; if(bytes+ld.length>maxBytes){if(truncated)*truncated=YES;break;} fwrite(ld.bytes,1,ld.length,f);bytes+=ld.length;methods++;} free(cms); } free(cs); fclose(f); if(classes>=maxClasses||methods>=maxMethods)if(truncated)*truncated=YES; return bytes;
}

static void AppendViewTree(UIView *v, NSUInteger depth, NSUInteger *nodes, NSMutableString *out) {
    if (!v || depth>kMaxStartupDepth || *nodes>=kMaxStartupNodes) return; (*nodes)++;
    [out appendFormat:@"%@%@\n", [@"" stringByPaddingToLength:depth*2 withString:@" " startingAtIndex:0], ViewLine(v)];
    for (UIView *child in [v.subviews copy]) AppendViewTree(child,depth+1,nodes,out);
}
static UIWindow *FindHostWindow(UIWindowScene **sceneOut, NSString **evidence) {
    UIApplication *app=UIApplication.sharedApplication; NSMutableString *log=[NSMutableString string]; UIWindow *best=nil; UIWindowScene *bestScene=nil;
    for (UIScene *s in app.connectedScenes) {
        if (![s isKindOfClass:UIWindowScene.class]) continue; UIWindowScene *ws=(UIWindowScene *)s;
        [log appendFormat:@"scene=%p state=%ld windows=%lu\n",ws,(long)ws.activationState,(unsigned long)ws.windows.count];
        if (ws.activationState!=UISceneActivationStateForegroundActive && ws.activationState!=UISceneActivationStateForegroundInactive) continue;
        for (UIWindow *w in ws.windows) { [log appendFormat:@"  window=%p hidden=%@ level=%.1f root=%@\n",w,w.hidden?@"YES":@"NO",w.windowLevel,w.rootViewController?NSStringFromClass(w.rootViewController.class):@"(nil)"]; if (!w.hidden && w.rootViewController && w.windowLevel==UIWindowLevelNormal && w.bounds.size.width>0 && w.bounds.size.height>0) { best=w; bestScene=ws; break; } }
        if (best) break;
    }
    if (sceneOut) *sceneOut=bestScene; if (evidence) *evidence=log; return best;
}

@interface InspectorWindow : UIWindow @end
@implementation InspectorWindow
- (UIView *)hitTest:(CGPoint)p withEvent:(UIEvent *)event { UIView *hit=[super hitTest:p withEvent:event]; if (hit==self || hit==self.rootViewController.view) return nil; return hit; }
@end

@class InspectorCore;
@interface InspectorRootController : UIViewController @property(nonatomic,weak) InspectorCore *core; @end
@interface InspectorButton : UIButton @property(nonatomic,weak) InspectorCore *core; @end


@interface SessionCapture : NSObject
@property(nonatomic,strong) NSString *sessionID;
@property(nonatomic,strong) NSMutableArray<NSDictionary *> *snapshots;
@property(nonatomic,weak) UIWindow *hostWindow;
@property(nonatomic) BOOL active;
+ (instancetype)shared;
- (void)start:(UIWindow *)host;
- (void)capture:(UIWindow *)host label:(NSString *)label inspectorWindow:(UIWindow *)inspector;
- (void)stop;
- (NSURL *)stageSession:(UIWindow *)host error:(NSError **)error;
@end

static void SessionViewSnapshot(UIView *v, NSUInteger depth, NSUInteger *nodes, NSUInteger limit, NSMutableArray *out, NSHashTable *seen) {
    if (!v || depth>8 || *nodes>=limit || [seen containsObject:v]) return;
    [seen addObject:v]; (*nodes)++;
    NSMutableDictionary *d=[@{ @"class":NSStringFromClass(v.class), @"superclass":NSStringFromClass(v.superclass), @"address":[NSString stringWithFormat:@"%p",v], @"frame":NSStringFromCGRect(v.frame), @"bounds":NSStringFromCGRect(v.bounds), @"alpha":@(v.alpha), @"hidden":@(v.hidden), @"opaque":@(v.opaque), @"backgroundColor":ColorString(v.backgroundColor), @"layerClass":NSStringFromClass(v.layer.class), @"cornerRadius":@(v.layer.cornerRadius), @"borderWidth":@(v.layer.borderWidth), @"borderColor":LayerColorString(v.layer.borderColor), @"sublayerCount":@(v.layer.sublayers.count), @"accessibilityIdentifier":v.accessibilityIdentifier ?: @"", @"superview":v.superview ? NSStringFromClass(v.superview.class) : @"(nil)" } mutableCopy];
    if ([v isKindOfClass:UIScrollView.class]) { UIScrollView *sv=(UIScrollView *)v; d[@"contentOffset"]=NSStringFromCGPoint(sv.contentOffset); d[@"contentSize"]=NSStringFromCGSize(sv.contentSize); }
    if ([v isKindOfClass:UICollectionViewCell.class] || [v isKindOfClass:UITableViewCell.class]) d[@"visibleCellClass"]=NSStringFromClass(v.class);
    [out addObject:d]; for(UIView *child in [v.subviews copy]) SessionViewSnapshot(child,depth+1,nodes,limit,out,seen);
}
static void SessionControllerSnapshot(UIViewController *vc, NSUInteger depth, NSUInteger *nodes, NSMutableArray *out, NSHashTable *seen) {
    if(!vc||depth>16||*nodes>=500||[seen containsObject:vc]) return; [seen addObject:vc]; (*nodes)++;
    NSMutableDictionary *d=[@{ @"class":NSStringFromClass(vc.class), @"superclass":NSStringFromClass(vc.superclass), @"address":[NSString stringWithFormat:@"%p",vc], @"childCount":@(vc.childViewControllers.count), @"presented":vc.presentedViewController ? NSStringFromClass(vc.presentedViewController.class) : @"(nil)" } mutableCopy];
    if([vc isKindOfClass:UINavigationController.class]) d[@"navigationStack"]=[[(UINavigationController *)vc viewControllers] valueForKeyPath:@"class.description"] ?: @[];
    if([vc isKindOfClass:UITabBarController.class]) d[@"selectedTab"]=(NSStringFromClass(((UITabBarController *)vc).selectedViewController.class) ?: @"(nil)");
    [out addObject:d]; for(UIViewController *c in vc.childViewControllers) SessionControllerSnapshot(c,depth+1,nodes,out,seen); SessionControllerSnapshot(vc.presentedViewController,depth+1,nodes,out,seen);
}
@implementation SessionCapture
+ (instancetype)shared { static SessionCapture *x; static dispatch_once_t once; dispatch_once(&once,^{x=[self new];}); return x; }
- (instancetype)init { if((self=[super init])) _snapshots=[NSMutableArray array]; return self; }
- (void)sceneChanged:(NSNotification *)note { if(!self.active||!self.hostWindow)return; dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(.5*NSEC_PER_SEC)),dispatch_get_main_queue(),^{ if(self.active)[self capture:self.hostWindow label:@"scene-activation" inspectorWindow:nil]; }); }
- (void)start:(UIWindow *)host { self.hostWindow=host; NSAssert(NSThread.isMainThread, @"UIKit capture must start on main"); self.sessionID=[NSUUID UUID].UUIDString; self.snapshots=[NSMutableArray array]; self.active=YES; [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(sceneChanged:) name:UIApplicationDidBecomeActiveNotification object:nil]; [self capture:host label:@"session-start" inspectorWindow:nil]; }
- (void)capture:(UIWindow *)host label:(NSString *)label inspectorWindow:(UIWindow *)inspector { if(!NSThread.isMainThread||!host||!self.active)return; NSUInteger vn=0,cn=0; NSMutableArray *views=[NSMutableArray array],*controllers=[NSMutableArray array]; SessionViewSnapshot(host,0,&vn,1200,views,[NSHashTable weakObjectsHashTable]); SessionControllerSnapshot(host.rootViewController,0,&cn,controllers,[NSHashTable weakObjectsHashTable]); NSMutableDictionary *snap=[@{ @"sessionID":self.sessionID ?: @"", @"captureID":[NSUUID UUID].UUIDString, @"timestamp":[NSDate date].description, @"label":label ?: @"", @"scene":host.windowScene ? host.windowScene.session.persistentIdentifier : @"", @"hostWindow":[NSString stringWithFormat:@"%p",host], @"views":views, @"controllers":controllers, @"truncated":@(vn>=2000||cn>=500), @"viewCount":@(vn), @"controllerCount":@(cn) } mutableCopy];
    UIGraphicsImageRenderer *renderer=[[UIGraphicsImageRenderer alloc] initWithSize:host.bounds.size]; UIImage *image=[renderer imageWithActions:^(UIGraphicsImageRendererContext *ctx){ [host drawViewHierarchyInRect:host.bounds afterScreenUpdates:NO]; }]; snap[@"screenshotData"]=UIImagePNGRepresentation(image) ?: [NSData data];
    NSDictionary *last=self.snapshots.lastObject; if(last && [last[@"views"] isEqual:views] && [last[@"controllers"] isEqual:controllers] && [last[@"label"] isEqual:label]) return; [self.snapshots addObject:snap];
}
- (void)stop { self.active=NO; [[NSNotificationCenter defaultCenter] removeObserver:self name:UIApplicationDidBecomeActiveNotification object:nil]; }
- (NSURL *)stageSession:(UIWindow *)host error:(NSError **)error { if(NSThread.isMainThread){[self capture:host label:@"export" inspectorWindow:nil];} NSURL *base=[NSURL fileURLWithPath:[NSTemporaryDirectory() stringByAppendingPathComponent:[NSString stringWithFormat:@"%@",self.sessionID ?: [NSUUID UUID].UUIDString]] isDirectory:YES]; [[NSFileManager defaultManager] createDirectoryAtURL:base withIntermediateDirectories:YES attributes:nil error:error]; if(error&&*error)return nil; [[NSFileManager defaultManager] createDirectoryAtURL:[base URLByAppendingPathComponent:@"Screens"] withIntermediateDirectories:YES attributes:nil error:nil]; NSMutableArray *index=[NSMutableArray array]; for(NSDictionary *snap in self.snapshots){ NSString *cid=snap[@"captureID"]; NSURL *dir=[[base URLByAppendingPathComponent:@"Screens"] URLByAppendingPathComponent:cid isDirectory:YES]; [[NSFileManager defaultManager] createDirectoryAtURL:dir withIntermediateDirectories:YES attributes:nil error:nil]; NSMutableDictionary *copy=[snap mutableCopy]; NSData *png=copy[@"screenshotData"]; [copy removeObjectForKey:@"screenshotData"]; [copy removeObjectForKey:@"views"]; [copy removeObjectForKey:@"controllers"]; [index addObject:copy]; [NSJSONSerialization dataWithJSONObject:snap[@"views"] options:NSJSONWritingPrettyPrinted error:nil]; [[NSJSONSerialization dataWithJSONObject:snap[@"views"] options:NSJSONWritingPrettyPrinted error:nil] writeToURL:[dir URLByAppendingPathComponent:@"views.json"] atomically:YES]; [[NSJSONSerialization dataWithJSONObject:snap[@"controllers"] options:NSJSONWritingPrettyPrinted error:nil] writeToURL:[dir URLByAppendingPathComponent:@"controllers.json"] atomically:YES]; [png writeToURL:[dir URLByAppendingPathComponent:@"screenshot.png"] atomically:YES]; } NSData *idx=[NSJSONSerialization dataWithJSONObject:@{ @"sessionID":self.sessionID ?: @"", @"snapshotCount":@(index.count), @"snapshots":index, @"coverage":@"Observed screens only; not 100% app coverage." } options:NSJSONWritingPrettyPrinted error:error]; [idx writeToURL:[base URLByAppendingPathComponent:@"SESSION_INDEX.json"] options:NSDataWritingAtomic error:error]; [@"This session records screens actually observed and captured. It does not claim full app coverage.\n" writeToURL:[base URLByAppendingPathComponent:@"COVERAGE_REPORT.txt"] atomically:YES encoding:NSUTF8StringEncoding error:nil]; return base; }
@end

@interface InspectorCore : NSObject <UIDocumentPickerDelegate>
@property(nonatomic,strong) InspectorWindow *window;
@property(nonatomic,strong) InspectorRootController *root;
@property(nonatomic,strong) InspectorButton *button;
@property(nonatomic,weak) UIWindow *hostWindow;
@property(nonatomic,weak) UIWindowScene *scene;
@property(nonatomic,strong) NSMutableString *startup;
@property(nonatomic) BOOL started;
@property(nonatomic,strong) NSURL *selectedFolder;
@property(nonatomic) BOOL collectionCancelled;
@property(nonatomic,strong) UIAlertController *collectionAlert;
@property(nonatomic) BOOL collectionRunning;
- (NSData *)detailedRuntimeJSON;
+ (instancetype)shared;
- (void)start;
- (void)showMenu;
- (void)exportReports;
- (void)runOneButtonCollection;
- (void)phasePrepare:(NSTimeInterval)jobStart;
- (void)phaseImages:(NSTimeInterval)jobStart;
- (void)phaseRuntime:(NSTimeInterval)jobStart;
- (void)phaseViews:(NSTimeInterval)jobStart;
- (void)phaseStatic:(NSTimeInterval)jobStart;
- (void)phaseFiles:(NSTimeInterval)jobStart;
- (void)phaseZip:(NSTimeInterval)jobStart;
- (void)phaseVerify:(NSTimeInterval)jobStart url:(NSURL *)url zip:(NSData *)zip stage:(NSURL *)stage error:(NSError *)error;
- (void)phaseShare:(NSTimeInterval)jobStart url:(NSURL *)url stage:(NSURL *)stage count:(NSUInteger)count;
- (void)finishCollection:(NSURL *)stage jobStart:(NSTimeInterval)jobStart error:(NSString *)error;
@end

@implementation InspectorButton
- (instancetype)initWithCore:(InspectorCore *)core { if((self=[super initWithFrame:CGRectMake(0,0,56,56)])){_core=core; self.accessibilityLabel=@"Universal UI Inspector"; self.backgroundColor=[UIColor colorWithRed:.05 green:.25 blue:.85 alpha:.96]; self.layer.cornerRadius=28; self.layer.borderWidth=2; self.layer.borderColor=UIColor.whiteColor.CGColor; self.layer.shadowColor=UIColor.blackColor.CGColor; self.layer.shadowOpacity=.45; self.layer.shadowRadius=5; [self setTitle:@"UI" forState:UIControlStateNormal]; [self setTitleColor:UIColor.whiteColor forState:UIControlStateNormal]; self.titleLabel.font=[UIFont boldSystemFontOfSize:15]; [self addTarget:self action:@selector(open:) forControlEvents:UIControlEventTouchUpInside]; UIPanGestureRecognizer *pan=[[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(drag:)]; [self addGestureRecognizer:pan]; } return self; }
- (void)open:(id)sender { [_core runOneButtonCollection]; }
- (void)drag:(UIPanGestureRecognizer *)g { UIView *v=self; CGPoint t=[g translationInView:v.superview]; if(g.state==UIGestureRecognizerStateChanged){CGPoint c=v.center; c.x+=t.x;c.y+=t.y; UIEdgeInsets insets=v.superview.safeAreaInsets; CGFloat r=28; c.x=MAX(insets.left+r,MIN(v.superview.bounds.size.width-insets.right-r,c.x)); c.y=MAX(insets.top+r,MIN(v.superview.bounds.size.height-insets.bottom-r,c.y)); v.center=c; [g setTranslation:CGPointZero inView:v.superview];} }
@end

@implementation InspectorRootController
- (void)viewDidLayoutSubviews { [super viewDidLayoutSubviews]; if(!self.core.button.superview) return; UIEdgeInsets insets=self.view.safeAreaInsets; if(CGRectIsEmpty(self.core.button.frame)||self.core.button.center.x<1){self.core.button.frame=CGRectMake(self.view.bounds.size.width-insets.right-70,insets.top+24,56,56);} else {CGPoint c=self.core.button.center; CGFloat r=28; c.x=MAX(insets.left+r,MIN(self.view.bounds.size.width-insets.right-r,c.x)); c.y=MAX(insets.top+r,MIN(self.view.bounds.size.height-insets.bottom-r,c.y)); self.core.button.center=c;} }
@end

@implementation InspectorCore
+ (instancetype)shared { static InspectorCore *x; static dispatch_once_t once; dispatch_once(&once,^{x=[self new];}); return x; }
- (instancetype)init { if((self=[super init])){_startup=[NSMutableString stringWithFormat:@"UniversalUIInspector startup %@\n",[NSDate date]];} return self; }
- (void)start { if(!NSThread.isMainThread){dispatch_async(dispatch_get_main_queue(),^{[self start];});return;} if(self.started && self.window.superview)return; UIWindowScene *scene=nil; NSString *evidence=nil; UIWindow *host=FindHostWindow(&scene,&evidence); [self.startup appendFormat:@"Discovery:\n%@",evidence ?: @"(none)"]; if(!host||!scene){[self.startup appendFormat:@"ERROR: no foreground usable host window\n"]; [self writeStartupReports]; return;} self.hostWindow=host; self.scene=scene; self.started=YES; self.root=[InspectorRootController new]; self.root.core=self; self.window=[[InspectorWindow alloc] initWithWindowScene:scene]; self.window.frame=scene.coordinateSpace.bounds; self.window.windowLevel=UIWindowLevelAlert+1; self.window.backgroundColor=UIColor.clearColor; self.window.opaque=NO; self.window.rootViewController=self.root; self.button=[[InspectorButton alloc] initWithCore:self]; [self.root.view addSubview:self.button]; self.window.hidden=NO; [self.root viewDidLayoutSubviews]; [self.startup appendFormat:@"Host window: %p %@\nScene: %p state=%ld\nOverlay created: %p visible=%@ button=%@\n",host,NSStringFromClass(host.class),scene,(long)scene.activationState,self.window,self.window.hidden?@"NO":@"YES",self.button]; [self writeStartupReports]; }
- (void)writeStartupReports { if(!NSThread.isMainThread){dispatch_async(dispatch_get_main_queue(),^{[self writeStartupReports];});return;} NSMutableString *tree=[NSMutableString stringWithString:@"STARTUP_VIEW_TREE.txt\n"]; NSUInteger nodes=0; AppendViewTree(self.hostWindow,0,&nodes,tree); [self.startup appendFormat:@"Startup tree nodes: %lu depth limit: %lu\n",(unsigned long)nodes,(unsigned long)kMaxStartupDepth]; NSString *boot=self.startup.copy; NSString *runtime=[NSString stringWithFormat:@"Runtime report %@\nloaded images: %u\nmain image: %s\ninspector window: %p\nhost window: %p\n",[NSDate date],_dyld_image_count(),_dyld_get_image_name(0) ?: "(nil)",self.window,self.hostWindow]; dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{WriteReport(@"BOOT_DIAGNOSTICS.txt",boot);WriteReport(@"RUNTIME_STARTUP_REPORT.txt",runtime);WriteReport(@"STARTUP_VIEW_TREE.txt",tree);}); }
- (UIViewController *)presenter { UIViewController *v=self.hostWindow.rootViewController; while(v.presentedViewController)v=v.presentedViewController; return v; }
- (NSString *)hierarchy { NSMutableString *s=[NSMutableString stringWithString:@"CURRENT_VIEW_HIERARCHY.txt\n"]; NSUInteger n=0; AppendViewTree(self.hostWindow,0,&n,s); return s; }
- (NSString *)controllers { NSMutableString *s=[NSMutableString stringWithString:@"CURRENT_CONTROLLERS.txt\n"]; UIViewController *v=self.hostWindow.rootViewController; [s appendFormat:@"root=%@\n",NSStringFromClass(v.class)]; while(v){[s appendFormat:@"%@ presented=%@ children=%lu\n",NSStringFromClass(v.class),v.presentedViewController?NSStringFromClass(v.presentedViewController.class):@"(nil)",(unsigned long)v.childViewControllers.count]; v=v.presentedViewController;} return s; }
- (NSString *)classes { int n=objc_getClassList(NULL,0); Class *cs=(Class *)malloc(sizeof(Class)*MAX(n,0)); n=objc_getClassList(cs,n); NSMutableString *s=[NSMutableString stringWithString:@"RUNTIME_CLASSES.txt\n"]; for(int i=0;i<n;i++){ Class c=cs[i]; [s appendFormat:@"%@ : %@\n",NSStringFromClass(c),NSStringFromClass(class_getSuperclass(c))]; unsigned mc=0; Method *ms=class_copyMethodList(c,&mc); for(unsigned j=0;j<mc;j++){Method m=ms[j];[s appendFormat:@"  instance %@ %p %s\n",NSStringFromSelector(method_getName(m)),method_getImplementation(m),method_getTypeEncoding(m)];} free(ms); unsigned pc=0; Method *pms=class_copyMethodList(object_getClass(c),&pc); for(unsigned j=0;j<pc;j++){Method m=pms[j];[s appendFormat:@"  class %@ %p %s\n",NSStringFromSelector(method_getName(m)),method_getImplementation(m),method_getTypeEncoding(m)];} free(pms); unsigned props=0; objc_property_t *ps=class_copyPropertyList(c,&props); for(unsigned j=0;j<props;j++) [s appendFormat:@"  property %s %s\n",property_getName(ps[j]),property_getAttributes(ps[j])]; free(ps); unsigned iv=0; Ivar *ivs=class_copyIvarList(c,&iv); for(unsigned j=0;j<iv;j++) [s appendFormat:@"  ivar %s %s offset=%td\n",ivar_getName(ivs[j]),ivar_getTypeEncoding(ivs[j]),ivar_getOffset(ivs[j])]; free(ivs); } free(cs); return s; }
- (NSData *)detailedRuntimeJSON { NSMutableArray *rows=[NSMutableArray array]; int n=objc_getClassList(NULL,0); Class *cs=(Class *)malloc(sizeof(Class)*MAX(n,0)); n=objc_getClassList(cs,n); for(int i=0;i<n;i++){Class c=cs[i]; NSMutableDictionary *row=[@{ @"class":NSStringFromClass(c), @"superclass":NSStringFromClass(class_getSuperclass(c)) ?: @"", @"image":class_getImageName(c) ? [NSString stringWithUTF8String:class_getImageName(c)] : @"" } mutableCopy]; NSMutableArray *methods=[NSMutableArray array]; unsigned mc=0; Method *ms=class_copyMethodList(c,&mc); for(unsigned j=0;j<mc;j++){Method m=ms[j]; Dl_info info={0}; dladdr((void *)method_getImplementation(m),&info); [methods addObject:@{ @"kind":@"instance", @"selector":NSStringFromSelector(method_getName(m)), @"typeEncoding":@(method_getTypeEncoding(m) ?: ""), @"imp":[NSString stringWithFormat:@"%p",method_getImplementation(m)], @"image":info.dli_fname ? [NSString stringWithUTF8String:info.dli_fname] : @"" }];} free(ms); Method *cms=class_copyMethodList(object_getClass(c),&mc); for(unsigned j=0;j<mc;j++){Method m=cms[j]; Dl_info info={0}; dladdr((void *)method_getImplementation(m),&info); [methods addObject:@{ @"kind":@"class", @"selector":NSStringFromSelector(method_getName(m)), @"typeEncoding":@(method_getTypeEncoding(m) ?: ""), @"imp":[NSString stringWithFormat:@"%p",method_getImplementation(m)], @"image":info.dli_fname ? [NSString stringWithUTF8String:info.dli_fname] : @"" }];} free(cms); row[@"methods"]=methods; NSMutableArray *props=[NSMutableArray array]; unsigned pc=0; objc_property_t *ps=class_copyPropertyList(c,&pc); for(unsigned j=0;j<pc;j++) [props addObject:@{ @"name":@(property_getName(ps[j]) ?: ""), @"attributes":@(property_getAttributes(ps[j]) ?: "") }]; free(ps); row[@"properties"]=props; NSMutableArray *ivars=[NSMutableArray array]; unsigned ic=0; Ivar *is=class_copyIvarList(c,&ic); for(unsigned j=0;j<ic;j++) [ivars addObject:@{ @"name":@(ivar_getName(is[j]) ?: ""), @"type":@(ivar_getTypeEncoding(is[j]) ?: ""), @"offset":@(ivar_getOffset(is[j])) }]; free(is); row[@"ivars"]=ivars; [rows addObject:row]; } free(cs); return [NSJSONSerialization dataWithJSONObject:@{ @"note":@"Objective-C runtime metadata only; not original source or Swift metadata.", @"classes":rows } options:NSJSONWritingPrettyPrinted error:nil]; }
- (NSString *)images { NSMutableString *s=[NSMutableString stringWithString:@"LOADED_IMAGES.txt\n"]; for(uint32_t i=0;i<_dyld_image_count();i++) [s appendFormat:@"%u base=%p slide=%ld %s\n",i,_dyld_get_image_header(i),_dyld_get_image_vmaddr_slide(i),_dyld_get_image_name(i) ?: "(nil)"]; return s; }
- (NSString *)diagnostics { return [NSString stringWithFormat:@"DIAGNOSTICS.txt\nmain thread=%@\nstarted=%@\nhost=%p\noverlay=%p hidden=%@\nreports=%@\n",NSThread.isMainThread?@"YES":@"NO",self.started?@"YES":@"NO",self.hostWindow,self.window,self.window.hidden?@"YES":@"NO",ReportsDirectory().path]; }
- (void)showMenu { if(!NSThread.isMainThread){dispatch_async(dispatch_get_main_queue(),^{[self showMenu];});return;} UIAlertController *a=[UIAlertController alertControllerWithTitle:@"Universal UI Inspector" message:@"Read-only diagnostics" preferredStyle:UIAlertControllerStyleActionSheet]; NSArray *items=@[ @[ @"Prepare Full Capture", ^{ [[SessionCapture shared] start:self.hostWindow]; } ], @[ @"Capture Current Screen", ^{ [[SessionCapture shared] capture:self.hostWindow label:@"manual" inspectorWindow:self.window]; } ], @[ @"Stop Capture", ^{ [[SessionCapture shared] stop]; } ], @[ @"Export Session", ^{ [self exportSession]; } ], @[ @"Choose Export Folder", ^{ [self chooseExportFolder]; } ], @[ @"Dump Visible Hierarchy", ^{ WriteReport(@"CURRENT_VIEW_HIERARCHY.txt",self.hierarchy); } ], @[ @"View Controllers", ^{ WriteReport(@"CURRENT_CONTROLLERS.txt",self.controllers); } ], @[ @"Runtime Classes (Detailed)", ^{ WriteReport(@"RUNTIME_CLASSES_DETAILED.txt",self.classes); [self.detailedRuntimeJSON writeToURL:[ReportsDirectory() URLByAppendingPathComponent:@"RUNTIME_CLASSES_DETAILED.json"] atomically:YES]; } ], @[ @"Loaded Images", ^{ WriteReport(@"LOADED_IMAGES.txt",self.images); } ], @[ @"Diagnostics", ^{ WriteReport(@"DIAGNOSTICS.txt",self.diagnostics); } ] ]; for(NSArray *item in items) [a addAction:[UIAlertAction actionWithTitle:item[0] style:UIAlertActionStyleDefault handler:^(__unused UIAlertAction *x){ ((void(^)(void))item[1])(); }]]; [a addAction:[UIAlertAction actionWithTitle:@"Close" style:UIAlertActionStyleCancel handler:nil]]; UIPopoverPresentationController *pop=a.popoverPresentationController; pop.sourceView=self.button; pop.sourceRect=self.button.bounds; pop.permittedArrowDirections=UIPopoverArrowDirectionAny; [[self presenter] presentViewController:a animated:YES completion:nil]; }

- (void)runOneButtonCollection { if(!NSThread.isMainThread){dispatch_async(dispatch_get_main_queue(),^{[self runOneButtonCollection];});return;} if(self.collectionRunning){return;} self.collectionRunning=YES; self.collectionCancelled=NO; NSTimeInterval jobStart=PhaseClock(); self.collectionAlert=[UIAlertController alertControllerWithTitle:@"Collecting runtime reports" message:@"Phase 1/9 — Preparation" preferredStyle:UIAlertControllerStyleAlert]; __weak typeof(self) weakSelf=self; [self.collectionAlert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:^(__unused UIAlertAction *a){weakSelf.collectionCancelled=YES; AppendPhaseLog(@"job",@"cancel-requested",jobStart,0,0,nil);}]]; [[self presenter] presentViewController:self.collectionAlert animated:YES completion:nil]; dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(.15*NSEC_PER_SEC)),dispatch_get_main_queue(),^{ [self phasePrepare:jobStart]; }); }
- (void)phasePrepare:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled during preparation"];return;} NSTimeInterval t=PhaseClock(); AppendPhaseLog(@"preparation",@"start",t,0,0,nil); self.collectionAlert.message=@"Phase 1/9 — Preparation"; NSURL *dir=ReportsDirectory(); NSString *state=[NSString stringWithFormat:@"job_start=%@\nlimits: classes=1200 methods=12000 report_bytes=8388608 views=1200 controllers=300\n",[NSDate date]]; [state writeToURL:[dir URLByAppendingPathComponent:@"JOB_STATE.txt"] atomically:YES encoding:NSUTF8StringEncoding error:nil]; AppendPhaseLog(@"preparation",@"end",t,1,state.length,nil); [self phaseImages:jobStart]; }
- (void)phaseImages:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled before loaded images"];return;} NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 2/9 — Loaded images"; NSString *text=self.images; WriteReport(@"LOADED_IMAGES.txt",text); AppendPhaseLog(@"loaded-images",@"end",t,_dyld_image_count(),text.length,nil); [self phaseRuntime:jobStart]; }
- (void)phaseRuntime:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled before runtime dump"];return;} NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 3/9 — Runtime classes (app-owned, bounded)"; NSURL *u=[ReportsDirectory() URLByAppendingPathComponent:@"RUNTIME_CLASSES_STREAM.txt"]; dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{BOOL trunc=NO;NSString *err=nil;NSUInteger bytes=WriteDetailedRuntimeReport(u,1200,12000,8*1024*1024,&trunc,&err);dispatch_async(dispatch_get_main_queue(),^{AppendPhaseLog(@"runtime-classes",trunc?@"truncated":(err?@"error":@"end"),t,1200,bytes,err);[self phaseViews:jobStart];});}); }
- (void)phaseViews:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled before views/controllers"];return;} NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 4/9 — Views/controllers (bounded)"; [[SessionCapture shared] start:self.hostWindow]; [[SessionCapture shared] capture:self.hostWindow label:@"one-button" inspectorWindow:self.window]; [[SessionCapture shared] stop]; NSUInteger count=[SessionCapture shared].snapshots.count; AppendPhaseLog(@"views-controllers",@"end",t,count,0,nil); [self phaseStatic:jobStart]; }
- (void)phaseStatic:(NSTimeInterval)jobStart { NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 5/9 — Static inspection: not run in dylib"; AppendPhaseLog(@"static-inspection",@"skipped",t,0,0,@"off-device analyzer only"); [self phaseFiles:jobStart]; }
- (void)phaseFiles:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled before file writing"];return;} NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 6/9 — Writing reports"; WriteReport(@"CURRENT_VIEW_HIERARCHY.txt",self.hierarchy); WriteReport(@"CURRENT_CONTROLLERS.txt",self.controllers); NSString *jsonSummary=@"{\n  \"format\": \"streamed-text\",\n  \"scope\": \"app-owned images\",\n  \"max_classes\": 1200,\n  \"max_methods\": 12000,\n  \"max_bytes\": 8388608\n}\n"; [jsonSummary writeToURL:[ReportsDirectory() URLByAppendingPathComponent:@"RUNTIME_CLASSES_DETAILED.json"] atomically:YES encoding:NSUTF8StringEncoding error:nil]; WriteReport(@"DIAGNOSTICS.txt",self.diagnostics); AppendPhaseLog(@"file-writing",@"end",t,4,jsonSummary.length,nil); [self phaseZip:jobStart]; }
- (void)phaseZip:(NSTimeInterval)jobStart { if(self.collectionCancelled){[self finishCollection:nil jobStart:jobStart error:@"cancelled before ZIP"];return;} NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 7/9 — Creating ZIP"; dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{NSError *err=nil;NSURL *stage=[[SessionCapture shared] stageSession:self.hostWindow error:&err];if(err||!stage){dispatch_async(dispatch_get_main_queue(),^{AppendPhaseLog(@"zip-creation",@"error",t,0,0,err.localizedDescription);[self finishCollection:nil jobStart:jobStart error:err.localizedDescription ?: @"staging failed"];});return;}NSMutableDictionary *files=[NSMutableDictionary dictionary];NSDirectoryEnumerator *it=[[NSFileManager defaultManager] enumeratorAtURL:stage includingPropertiesForKeys:nil options:0 errorHandler:nil];NSUInteger total=0;for(NSURL *u in it)if(!u.hasDirectoryPath){BOOL trunc=NO;NSData *d=BoundedFileData(u,2*1024*1024,&trunc);if(total+d.length>16*1024*1024)break;files[[u.path substringFromIndex:stage.path.length+1]]=d;total+=d.length;}NSURL *reports=ReportsDirectory();for(NSString *name in @[@"CURRENT_VIEW_HIERARCHY.txt",@"CURRENT_CONTROLLERS.txt",@"RUNTIME_CLASSES_STREAM.txt",@"RUNTIME_CLASSES_DETAILED.json",@"LOADED_IMAGES.txt",@"DIAGNOSTICS.txt",@"SESSION_PHASE_LOG.txt"]){BOOL trunc=NO;NSData *d=BoundedFileData([reports URLByAppendingPathComponent:name],2*1024*1024,&trunc);if(total+d.length<=16*1024*1024){files[[NSString stringWithFormat:@"Runtime/%@",name]]=d;total+=d.length;}}NSData *zip=ZipData(files);NSURL *url=[stage URLByAppendingPathComponent:@"UniversalUIInspector-Runtime-Session.zip"];[zip writeToURL:url options:NSDataWritingAtomic error:&err];dispatch_async(dispatch_get_main_queue(),^{AppendPhaseLog(@"zip-creation",err?@"error":@"end",t,files.count,zip.length,err.localizedDescription);[self phaseVerify:jobStart url:url zip:zip stage:stage error:err];});}); }
- (void)phaseVerify:(NSTimeInterval)jobStart url:(NSURL *)url zip:(NSData *)zip stage:(NSURL *)stage error:(NSError *)error { NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 8/9 — Verifying ZIP";NSUInteger count=0;NSString *why=nil;BOOL ok=!error&&ValidateZipArchive(zip,&count,&why);AppendPhaseLog(@"zip-verification",ok?@"end":@"error",t,count,zip.length,ok?nil:why);if(!ok){[self finishCollection:stage jobStart:jobStart error:why ?: @"ZIP verification failed"];return;}[self phaseShare:jobStart url:url stage:stage count:count]; }
- (void)phaseShare:(NSTimeInterval)jobStart url:(NSURL *)url stage:(NSURL *)stage count:(NSUInteger)count { NSTimeInterval t=PhaseClock(); self.collectionAlert.message=@"Phase 9/9 — Opening share sheet";AppendPhaseLog(@"share-sheet",@"start",t,count,0,nil);[self.collectionAlert dismissViewControllerAnimated:YES completion:^{self.collectionRunning=NO;UIActivityViewController *share=[[UIActivityViewController alloc] initWithActivityItems:@[url] applicationActivities:nil];UIPopoverPresentationController *pop=share.popoverPresentationController;pop.sourceView=self.button;pop.sourceRect=self.button.bounds;[[self presenter] presentViewController:share animated:YES completion:^{AppendPhaseLog(@"share-sheet",@"end",t,count,0,nil);}];}]; }
- (void)finishCollection:(NSURL *)stage jobStart:(NSTimeInterval)jobStart error:(NSString *)error { AppendPhaseLog(@"job",error&&[error isEqualToString:@"cancelled"]?@"cancelled":@"partial",jobStart,0,0,error); WriteReport(@"EXPORT_ERROR.txt",error ?: @"partial export"); self.collectionRunning=NO; if(self.collectionAlert.presentingViewController){self.collectionAlert.message=error ?: @"Partial export preserved";[self.collectionAlert dismissViewControllerAnimated:YES completion:^{if(stage){UIActivityViewController *share=[[UIActivityViewController alloc] initWithActivityItems:@[stage] applicationActivities:nil];[[self presenter] presentViewController:share animated:YES completion:nil];}}];} }

- (void)chooseExportFolder { UIDocumentPickerViewController *picker=[[UIDocumentPickerViewController alloc] initWithDocumentTypes:@[@"public.folder"] inMode:UIDocumentPickerModeOpen]; picker.delegate=self; [[self presenter] presentViewController:picker animated:YES completion:nil]; }
- (void)documentPicker:(UIDocumentPickerViewController *)controller didPickDocumentsAtURLs:(NSArray<NSURL *> *)urls { NSURL *u=urls.firstObject; if(!u)return; if([u startAccessingSecurityScopedResource]){self.selectedFolder=u; [self.startup appendFormat:@"Selected export folder: %@\n",u.path];} }
- (void)exportSession { dispatch_async(dispatch_get_main_queue(),^{ NSError *err=nil; NSURL *stage=[[SessionCapture shared] stageSession:self.hostWindow error:&err]; if(!stage){WriteReport(@"SESSION_EXPORT_ERROR.txt",err.localizedDescription ?: @"Unknown error");return;} NSMutableDictionary *files=[NSMutableDictionary dictionary]; NSDirectoryEnumerator *it=[[NSFileManager defaultManager] enumeratorAtURL:stage includingPropertiesForKeys:nil options:0 errorHandler:nil]; for(NSURL *u in it){if(!u.hasDirectoryPath){NSString *rel=[u.path substringFromIndex:stage.path.length+1]; NSData *d=[NSData dataWithContentsOfURL:u];if(d)files[rel]=d;}} NSData *zip=ZipData(files); NSURL *local=[stage URLByAppendingPathComponent:@"UniversalUIInspector-Session.zip"]; [zip writeToURL:local atomically:YES]; NSURL *target=self.selectedFolder ? [self.selectedFolder URLByAppendingPathComponent:local.lastPathComponent] : local; if(self.selectedFolder){NSError *copyError=nil; [[NSFileManager defaultManager] removeItemAtURL:target error:nil]; [[NSFileManager defaultManager] copyItemAtURL:local toURL:target error:&copyError]; if(copyError) WriteReport(@"SESSION_EXPORT_ERROR.txt",copyError.localizedDescription);} UIActivityViewController *share=[[UIActivityViewController alloc] initWithActivityItems:@[target] applicationActivities:nil]; UIPopoverPresentationController *pop=share.popoverPresentationController;pop.sourceView=self.button;pop.sourceRect=self.button.bounds;[[self presenter] presentViewController:share animated:YES completion:nil]; }); }
- (void)exportReports { dispatch_async(dispatch_get_main_queue(),^{ NSArray *names=@[@"BOOT_DIAGNOSTICS.txt",@"RUNTIME_STARTUP_REPORT.txt",@"STARTUP_VIEW_TREE.txt",@"CURRENT_VIEW_HIERARCHY.txt",@"CURRENT_CONTROLLERS.txt",@"RUNTIME_CLASSES.txt",@"LOADED_IMAGES.txt",@"DIAGNOSTICS.txt"]; NSMutableDictionary *files=[NSMutableDictionary dictionary]; for(NSString *n in names){NSData *d=[NSData dataWithContentsOfFile:ReportPath(n)];if(d)files[n]=d;} NSData *zip=ZipData(files); NSURL *url=[ReportsDirectory() URLByAppendingPathComponent:@"UniversalUIInspector-Reports.zip"]; [zip writeToURL:url atomically:YES]; UIActivityViewController *share=[[UIActivityViewController alloc] initWithActivityItems:@[url] applicationActivities:nil]; UIPopoverPresentationController *pop=share.popoverPresentationController; pop.sourceView=self.button;pop.sourceRect=self.button.bounds; UIViewController *p=[self presenter]; [p presentViewController:share animated:YES completion:nil]; }); }
@end

static void UniversalUIInspectorInit(void) { dispatch_async(dispatch_get_main_queue(),^{ InspectorCore *core=InspectorCore.shared; NSArray *delays=@[@0.5,@1.0,@2.0,@4.0]; for(NSNumber *delay in delays) dispatch_after(dispatch_time(DISPATCH_TIME_NOW,(int64_t)(delay.doubleValue*NSEC_PER_SEC)),dispatch_get_main_queue(),^{if(!core.started)[core start];}); }); }
__attribute__((constructor)) static void UniversalUIInspectorConstructor(void) { UniversalUIInspectorInit(); }
